# Generated by Django 5.1.1 on 2024-11-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_student_last_activity_date_student_streak_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='base.subject'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.subject'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='base.subject'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
