# Generated by Django 5.1.1 on 2024-11-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_flashcard_code_notes_code_quiz_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='chapter',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='chapter',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='chapter',
            new_name='subject',
        ),
    ]
